Update npm-publish.yml
editor-js/code pull request #66
Opened 2023-11-13 13:58 UTC by GoldenJaden

There is a common workflow now in different repository (https://github.com/codex-team/github-workflows) and it's being called from all the tools.

This is done to simplify version control and general convenience.

2023-11-14 14:59 UTC, neSpecc approved these changes

2023-11-18 18:31 UTC, gohabereg approved these changes

2023-11-18 18:34 UTC, robonetphy commented
pls remove the conflict

2023-11-18 18:34 UTC, robonetphy requested changes
remove conflict

2023-11-19 10:38 UTC, GoldenJaden reviewed
Fixed conflict

2023-11-21 11:59 UTC, closed without merging